### ISSUE TITLE
Crash because ModContainer.triggerMap was removed in forge 1.16.2-33.0.30

### ISSUE THREAD

**Issue by lhns** [Kotori316/SLP#7]
In the following commit ```ModContainer.triggerMap``` was removed: https://github.com/MinecraftForge/MinecraftForge/commit/d76ee4edd74d98db274578922ebbf023c1d6d522#diff-8e1cfb1483294fa0e650c5e32042eabfL58
```diff
- protected final Map<ModLoadingStage, Consumer<LifecycleEventProvider.LifecycleEvent>> triggerMap;
+ protected final Map<ModLoadingStage, Runnable> activityMap = new HashMap<>();
```

In forge 1.16.2-33.0.23 and below everything works fine but since 1.16.2-33.0.30 the game crashes.

```
[02Sep2020 15:59:19.350] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.kotori316.scala_lib.ScalaLanguageTarget.loadMod(ScalaLanguageTarget.scala:19) ~[?:2.13.3-build-1]
	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:297) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$buildMods$24(ModLoader.java:277) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_261]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
	at scala.collection.convert.JavaCollectionWrappers$MapWrapper$$anon$2$$anon$3.forEachRemaining(JavaCollectionWrappers.scala:232) ~[?:2.13.3-build-1]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:279) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$7(ModLoader.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:53) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.2-33.0.32.jar:33.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.2-33.0.32.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.2-33.0.32.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.2-33.0.32.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
	at com.kotori316.scala_lib.ScalaLanguageTarget.loadMod(ScalaLanguageTarget.scala:15) ~[?:2.13.3-build-1]
	... 37 more
Caused by: java.lang.NoSuchFieldError: triggerMap
	at com.kotori316.scala_lib.ScalaModContainer.<init>(ScalaModContainer.java:54) ~[?:2.13.3-build-1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
	at com.kotori316.scala_lib.ScalaLanguageTarget.loadMod(ScalaLanguageTarget.scala:15) ~[?:2.13.3-build-1]
	... 37 more
```

**Comment by Kotori316** [comment]
I uploaded v2.13.3-build-3.
As I saw the log of CI result, this problem is fixed.

**Comment by lhns** [comment]
well that was fast 😂
